2020-08-09 15:08:02,040 INFO 177457: Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
1711108
Traceback (most recent call last):
  File "shard.py", line 302, in <module>
    shard_dataset()
  File "/home/groups/rondror/software/sidhikab/miniconda/envs/geometric/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/groups/rondror/software/sidhikab/miniconda/envs/geometric/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/groups/rondror/software/sidhikab/miniconda/envs/geometric/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/groups/rondror/software/sidhikab/miniconda/envs/geometric/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "shard.py", line 59, in shard_dataset
    Sharded.shard_one(ensemble_map, sharded_path, start, stop, shard_num)
  File "shard.py", line 110, in shard_one
    sharded._write_shard(shard_num, df)
  File "shard.py", line 273, in _write_shard
    metadata = pd.concat((pd.read_hdf(metadata_path, f'metadata'),
  File "/home/groups/rondror/software/sidhikab/miniconda/envs/geometric/lib/python3.8/site-packages/pandas/io/pytables.py", line 420, in read_hdf
    return store.select(
  File "/home/groups/rondror/software/sidhikab/miniconda/envs/geometric/lib/python3.8/site-packages/pandas/io/pytables.py", line 814, in select
    return it.get_result()
  File "/home/groups/rondror/software/sidhikab/miniconda/envs/geometric/lib/python3.8/site-packages/pandas/io/pytables.py", line 1829, in get_result
    results = self.func(self.start, self.stop, where)
  File "/home/groups/rondror/software/sidhikab/miniconda/envs/geometric/lib/python3.8/site-packages/pandas/io/pytables.py", line 798, in func
    return s.read(start=_start, stop=_stop, where=_where, columns=columns)
  File "/home/groups/rondror/software/sidhikab/miniconda/envs/geometric/lib/python3.8/site-packages/pandas/io/pytables.py", line 3070, in read
    values = self.read_array(f"block{i}_values", start=_start, stop=_stop)
  File "/home/groups/rondror/software/sidhikab/miniconda/envs/geometric/lib/python3.8/site-packages/pandas/io/pytables.py", line 2719, in read_array
    node = getattr(self.group, key)
  File "/home/groups/rondror/software/sidhikab/miniconda/envs/geometric/lib/python3.8/site-packages/tables/group.py", line 836, in __getattr__
    return self._f_get_child(name)
  File "/home/groups/rondror/software/sidhikab/miniconda/envs/geometric/lib/python3.8/site-packages/tables/group.py", line 708, in _f_get_child
    self._g_check_has_child(childname)
  File "/home/groups/rondror/software/sidhikab/miniconda/envs/geometric/lib/python3.8/site-packages/tables/group.py", line 393, in _g_check_has_child
    raise NoSuchNodeError(
tables.exceptions.NoSuchNodeError: group ``/metadata`` does not have a child named ``block0_values``
Closing remaining open files:/oak/stanford/groups/rondror/projects/combind/flexibility/atom3d/sharded/ligands_meta_500.h5...done
